### ISSUE TITLE
Not getting game info

### ISSUE THREAD

**Issue by SJang1** [rishubil/TrickyTowersUtils#10]
![image](https://user-images.githubusercontent.com/29011440/53565474-f3a31900-3b9c-11e9-8fb6-a487275bae84.png)

**Comment by SJang1** [comment]
On Online cup puzzle mode, one person had left before (at the past game)
Happened after shutting down, restart and start the game.
Needed to restart Tricky Towers

**Comment by rishubil** [comment]
It seems same issue with #2
