### ISSUE TITLE
WinError 10049

### ISSUE THREAD

**Issue by SJang1** [rishubil/TrickyTowersUtils#11]
![image](https://user-images.githubusercontent.com/29011440/53611889-78c91500-3c13-11e9-9bfe-5bfde0d2cdc3.png)

![image](https://user-images.githubusercontent.com/29011440/53611913-8c747b80-3c13-11e9-8aec-5b68ad387954.png)
(Overlay)

Ran while trickytower is running.

config.ini : 
```ini
[Server]
host=0.0.0.0
port=8082
secret_key=1q2w3e4r
debug=true

[Observer]
host=0.0.0.0
port=8082
delay=0.5
debug=true

[Overlay]
debug=true
highlight_76561198901664805=false
```

**Comment by rishubil** [comment]
It's not a bug. `0.0.0.0` cannot be used for the observer's host value.
`0.0.0.0` is a non-routable meta-address used to designate an invalid, unknown or non applicable target.
You can find more information [here](https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0).
