### ISSUE TITLE
ERROR: 'The token does not have the specified privilege'

### ISSUE THREAD

**Issue by semir4in** [rishubil/TrickyTowersUtils#18]
I set ASCII `hostname` and correct `secret_key` in 'config.ini' file

I just got a error with following observer log:
![tt_error](https://user-images.githubusercontent.com/41550222/56661544-e7d75d00-66dc-11e9-8e42-6a9814fd2766.png)

And also, unlikely #16, i saw these repeated time parsing message:
```python
def parse(pm):
    print(f'\n--- Parse at {int(time() * 1000)} ---')
```

Is this a problem of my setting or something?
Please help

thank you in advance :D

**Comment by rishubil** [comment]
It looks normal.

Did you have any problems to use overlay? Or, are you just worrying about the log message?

**Comment by semir4in** [comment]
Under the setting avobe, I could not see overlay panel in `http://127.0.0.1:8082/overlay` in online cup game.
But I checked just a single time so I will check again soon!
I will tell you If that was a unlucky glitch or not

**Comment by rishubil** [comment]
You can also check parsed result by change server's debug option on your `config.ini` file.

https://github.com/rishubil/TrickyTowersUtils/blob/ead6f290f5e4d7fdc6226d613b8cded3c3f6926c/config(example).ini#L5

This option make server to print the parsed result on log window.

**Comment by semir4in** [comment]
Today, I get a fine overlay :D
![done](https://user-images.githubusercontent.com/41550222/56747494-0dd22f80-67b9-11e9-89c8-fc4a39398c2e.PNG)
I think that was a glitch. thank you!
